#!/bin/bash

# 1. First, directly modify the GeneratedPluginRegistrant.h file
PLUGIN_REG_PATH="ios/Runner/GeneratedPluginRegistrant.h"
if [ -f "$PLUGIN_REG_PATH" ]; then
  # Back up the original file
  cp "$PLUGIN_REG_PATH" "${PLUGIN_REG_PATH}.bak"
  
  # Create a new GeneratedPluginRegistrant.h without Flutter.h dependency
  cat > "$PLUGIN_REG_PATH" << 'EOF'
// This file is generated by Flutter. Do not edit.

// GeneratedPluginRegistrant.h - modified to remove Flutter.h dependency

#ifndef GeneratedPluginRegistrant_h
#define GeneratedPluginRegistrant_h

// Replacing Flutter.h with direct declarations
typedef struct _FlutterEngine* FlutterEngine;
typedef struct _FlutterViewController* FlutterViewController;
typedef void (^FlutterApplicationLifeCycleDelegate)(void);

@interface FlutterPluginRegistry : NSObject
- (instancetype)initWithViewController:(FlutterViewController *)flutterViewController;
@end

@protocol FlutterPlugin <NSObject>
@required
+ (void)registerWithRegistrar:(NSObject *)registrar;
@end

@interface GeneratedPluginRegistrant : NSObject
+ (void)registerWithRegistry:(NSObject *)registry;
@end

#endif /* GeneratedPluginRegistrant_h */
EOF
fi

# 2. Create a properly structured Flutter directory
mkdir -p ios/Pods/Headers/Public/Flutter
mkdir -p ios/Flutter.framework/Headers

# 3. Create a minimal Flutter.h file
cat > ios/Pods/Headers/Public/Flutter/Flutter.h << 'EOF'
#ifndef FLUTTER_FLUTTER_H_
#define FLUTTER_FLUTTER_H_

#import <UIKit/UIKit.h>

typedef struct _FlutterEngine* FlutterEngine;
typedef struct _FlutterViewController* FlutterViewController;

@protocol FlutterPlugin <NSObject>
@required
+ (void)registerWithRegistrar:(NSObject *)registrar;
@end

#endif  // FLUTTER_FLUTTER_H_
EOF

# 4. Copy the Flutter.h file to Flutter.framework/Headers
cp ios/Pods/Headers/Public/Flutter/Flutter.h ios/Flutter.framework/Headers/

# 5. Create symbolic links in the project
cd ios
mkdir -p Runner.xcodeproj/Flutter
ln -sf ../Flutter.framework Runner.xcodeproj/Flutter/
cd ..

echo "Files created successfully. Now run:"
echo "cd ios"
echo "pod install"
echo "cd .."
echo "fvm flutter build ios"