enum PushyMessageTypeEnum {
  None,
  GateStatus,
  SendJobCard,
  ConfirmAppUsage,
  ActualJobError,
  WeightCardIncoming,
  ExitThePort,
  GateStatusReject,
  GateStatusMoveTroubleGate,
  GateStatusMoveToManualInspect,
  GateStatusMoveToCustom,
  GateStatusSendToPort,
  GateStatusExit,
  NotAcceptedApp,
  GateStatusSendSupport,
  WaitingJobCard,
  SuccessfullyVerified
}
